name: Staging Deployment

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.18.0]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM install
        run: npm install
      - name: Production build
        run: npm run build
        env:
          VITE_CHAIN_ID: "mainnet"
          VITE_GATEWAY_BASE_URL: "https://mainnet.rpc.grove.city/v1/60a2ac11b1747c6552385c61"
          VITE_TX_FEE: "10000"
          VITE_MAX_TRANSACTION_LIST_COUNT: "5000"
          VITE_MIN_TRANSACTION_LIST_COUNT: "200"
          VITE_BLOCK_EXPLORER_BASE_URL: "https://poktscan.com"
          VITE_BUY_POKT_BASE_URL: "https://forum.pokt.network/t/secondary-markets-for-pokt/629"
          VITE_POKT_USD_VALUE: ${{ secrets.POKT_USD_MARKET_PRICE }}
          VITE_HTTP_TIMEOUT: 0
          VITE_HTTP_HEADERS: '{"Content-Type": "application/json"}'
          VITE_USE_LEGACY_CODEC: "false"
      - name: Deploy to GCS
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: portal-gb-prod
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        with:
          args: -m rsync -r ./build gs://pocket-wallet-staging-frontend
          cli: gsutil
      - name: Clear Cloud CDN Cache
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: portal-gb-prod
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        with:
          args: compute url-maps invalidate-cdn-cache wallet-staging-url-map --path \"/*\"
